config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # resources :wordings
  resources :students do
    resources :payments, only: %i[new create destroy]
    get '/payments', to: "payments#student_index", as: :student_payment_index
  end

  resources :lessons do
    resources :lesson_comments, only: %i[show new create]
  end

  get "users", to: "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :student, class_name: 'User'
  belongs_to :teacher, class_name: 'User'
  has_one :lesson_comment, dependent: :destroy
end

app/models/lesson_comment.rb
class LessonComment < ApplicationRecord
  belongs_to :lesson
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :student
  validates :price, presence: true
  validates :month, presence: true
  enum :month, {
    january: "January",
    february: "February",
    march: "March",
    april: "April",
    may: "May",
    june: "June",
    july: "July",
    august: "August",
    september: "September",
    october: "October",
    november: "November",
    december: "December"
  }
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :payments, dependent: :destroy
  has_many :day_hour_classes, inverse_of: :student
  accepts_nested_attributes_for :day_hour_classes, reject_if: :all_blank, allow_destroy: true

  validates :full_name, presence: true
  validates :language, presence: true
  validates :cpf, presence: true, uniqueness: true
  validates :birthdate, presence: true
  validates :payday, presence: true

  enum :level, {
    basic_one: 'Básico 1',
    basic_two: 'Básico 2',
    basic_three: 'Básico 3',
    intermediary_one: 'Intermediário 1',
    intermediary_two: 'Intermediário 2',
    intermediary_three: 'Intermediário 3',
    advanced_one: 'Avançado 1',
    advanced_two: 'Avançado 2',
    advanced_three: 'Avançado 3'
  }

  enum :payday, {
    day_1: 'Dia 01',
    day_5: 'Dia 05',
    day_10: 'Dia 10',
    day_20: 'Dia 20'
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  before_save :set_default_role

  has_many :lessons

  enum :role, {
    admin: 'Admin',
    teacher: 'Professor',
    student: 'Aluno'
  }

  def set_default_role
    self.role ||= :student
  end
end

app/models/wording.rb
class Wording < ApplicationRecord
  # belongs_to :user

  enum :level, {
    beginner: 'Iniciante',
    intermediary: 'Intermediário',
    advanced: 'Avançado'
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :role, :first_name, :last_name, :identification_number, :phone) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :current_password, :role, :first_name, :last_name, :identification_number, :phone) }
  end

  private

  def user_not_authorized
    flash[:alert] = "Você não está autorizado a executar esta ação."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/lesson_comments_controller.rb
class LessonCommentsController < ApplicationController
  before_action :set_lesson, only: [:show, :new, :create]

  def show
    @lesson_comment = @lesson.lesson_comment
  end

  def new
    @lesson_comment = LessonComment.new
  end

  def create
    @lesson_comment = LessonComment.new(lesson_comment_params)
    @lesson_comment.lesson = @lesson
    if @lesson_comment.save
      redirect_to lessons_path
    else
      render :new
    end
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:lesson_id])
  end

  def lesson_comment_params
    params.require(:lesson_comment).permit(:content)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show]

  def index
    @lessons = Lesson.where(teacher_id: current_user.id)
    @teachers = Lesson.distinct.pluck(:teacher_id)
  end

  def show
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)
    @lesson.teacher = current_user
    if @lesson.save
      redirect_to lessons_path
    else
      render :new
    end
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:day_hour, :student_id, :teacher_id, :language)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @student = Student.new
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_student, only: %i[new create student_index destroy]
  before_action :set_payment, only: %i[destroy]
  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.new(payment_params)
    @payment.student_id = @student.id
    if @payment.save
      redirect_to student_student_payment_index_path(@student.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def student_index
    @payments = Payment.where(student_id: params[:student_id])
  end

  def destroy
    @payment.destroy
    redirect_to student_student_payment_index_path(student_id: @student.id), notice: "Student was successfully destroyed", status: :see_other
  end

  private

  def set_payment
    @payment = Payment.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:price, :month, :student_id)
  end

  def set_student
    @student = Student.find(params[:student_id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[edit update destroy show]
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to student_path(@student)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @student_lessons = (1..(@student.monthly_lessons)).to_a
    @student_classes_given = (1..(@student.class_given)).to_a
  end

  def edit; end

  def update
    @student.update(student_params)
    redirect_to students_path
  end

  def destroy
    @student.destroy
    redirect_to students_path notice: "Student was successfully destroyed", status: :see_other
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :monthly_lessons, :language, :level, :current_month, lessons_attributes: [:id, :day, :hour])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/wordings_controller.rb
class WordingsController < ApplicationController
  before_action :set_wording, only: %i[show edit update destroy]

  def index
    @wordings = Wording.all
    authorize @wordings
  end

  def show
  end

  def new
    @wording = Wording.new
    authorize @wording
  end

  def create
    @wording = Wording.new(wording_params)
    authorize @wording
    if @wording.save
      redirect_to wording_path(@wording)
    else
      render :new
    end
  end

  def edit
    authorize @wording
  end

  def update
    authorize @wording
    if @wording.update(wording_params)
      redirect_to wording_path(@wording)
    else
      render :edit
    end
  end

  def destroy
    authorize @wording
    @wording.destroy
    redirect_to wordings_path
  end

  private

  def set_wording
    @wording = Wording.find(params[:id])
  end

  def wording_params
    params.require(:wording).permit(:text, :level, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyPeasyIdiomas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/lesson_comments/new.html.erb
<div class="container">
  <h1 class="title-text">Criando o resumo da aula...</h1>

  <%= simple_form_for [@lesson, @lesson_comment] do |f| %>
    <div class="row student-text">
      <%= f.input :content %>
    </div>
    <%= f.submit class: 'btn btn-success' %>
    <%= link_to 'Back', lessons_path, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/lesson_comments/show.html.erb
<div class="container mt-5">
  <h1 class="title-text">Resumo da aula:</h1>

  <hr>

  <h3>Escrito por: Prof <%= @lesson_comment.lesson.teacher.first_name %></h3>
  <h3>Aluno(a): <%= @lesson_comment.lesson.student.first_name %></h3>

  <hr>

  <h2>Comentário: <%= @lesson_comment.content %></h2>

  <%= link_to "Voltar", lessons_path, class: "btn btn-primary mt-5" %>
</div>

app/views/lessons/index.html.erb
<% @teachers.each do |teacher| %>
  <ol>
    <li><%= User.find(teacher).first_name %></li>
  </ol>
  <ul>
    <% @lessons.where(teacher_id: teacher).each do |lesson| %>
      <li>
        <%= lesson.student.first_name %>
        <%= lesson.day_hour.strftime("%d/%m/%Y %H:%M") %>
        <% if lesson.lesson_comment.present? %>
          <%= link_to "Resumo da aula", lesson_lesson_comment_path(lesson.id, lesson.lesson_comment.id) %>
        <% else %>
          <%= link_to "Criar resumo", new_lesson_lesson_comment_path(lesson.id) %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/lessons/new.html.erb
<div class="container">
  <h1 class="title-text">Criar uma nova aula</h1>

  <%= simple_form_for @lesson do |f| %>
    <div class="row student-text">
      <%= f.input :day_hour %>
    </div>
    <div class="row student-text">
      <%= f.input :student_id %>
    </div>
    <div class="row student-text">
      <%= f.input :teacher_id %>
    </div>
    <%= f.submit class: 'btn btn-success' %>
    <%= link_to 'Back', root_path, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/pages/_banner.html.erb
<div class="banner d-flex align-items-center">
  <div class="d-flex justify-content-center flex-column h-25 banner-text">
    <h1>TAKE THE PINK PILL</h1>
    <h4>Aprenda hoje mesmo um novo idioma! Seja para trabalho, <br> mestrado, viagem ou para entender suas séries, filmes, <br> doramas ou animes favoritos!</h4>
    <a class="btn btn-flat banner-btn" href="#">Matricule-se agora!</a>
  </div>
</div>

app/views/pages/_day_hour_classes.html.erb
<div class='nested-fields'>
  <%= f.input :day %>
  <%= f.input :hour %>
  <%= link_to_remove_association "remove day and hour", f %>
</div>

app/views/pages/_form_apply.html.erb
<style>
  /* .new_student form class */
  .new_student {
    width: 100%;
  }
</style>
<div class="col-md-12 d-flex flex-column align-items-center">
  <%= simple_form_for student do |f| %>
    <%= f.input :full_name, label: 'Nome completo' %>
    <%= f.input :cpf, label: "CPF" %>
    <%= f.input :birthdate, as: :string, input_html: { id: 'birthdate_input' }, label: "Data de nascimento" %>
    <div class="d-flex justify-content-between">
      <%= f.input :payday, collection: Student.paydays.values, label: "Melhor dia de pagamento" %>
      <%# f.input :language, collection: Student.languages.values, label: "Idioma desejado" %>
    </div>
    <div class="d-flex justify-content-end w-100">
      <%= f.button :submit, class: "btn btn-flat banner-btn", value: "Escolher o plano" %>
    </div>
  <% end %>
</div>

<script src="pikaday.js"></script>
<script>
  var picker = new Pikaday({ 
                            field: document.getElementById('birthdate_input'),
                            format: 'dd/mm/yyyy',
                            yearRange: [1950, <%= Date.today.year %>]
                          });
</script>

app/views/pages/_timeline.html.erb
<h1 class="project-name my-5 col-12">Qual será seu próximo idioma?</h1>
<div class="timeline col-md-12 col-lg-6 ms-5">
  <div id="timeline">
    <div class="timeline-item">
      <div class="timeline-icon">
        <span class="fi fi-us flag-country"></span>
      </div>
      <div class="timeline-content">
        <h2>INGLÊS</h2>
        <p class="mt-3">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
          Atque, facilis quo maiores magnam modi ab libero praesentium blanditiis.
        </p>
        <a class="btn btn-flat banner-btn" href="#">Aprenda inglês agora!</a>
      </div>
    </div>

    <div class="timeline-item">
      <div class="timeline-icon">
        <span class="fi fi-es flag-country"></span>
      </div>
      <div class="timeline-content right">
        <h2>ESPANHOL</h2>
        <p class="mt-3">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, facilis quo. Maiores magnam modi ab libero praesentium blanditiis consequatur aspernatur accusantium maxime molestiae sunt ipsa.
        </p>
        <a class="btn btn-flat banner-btn" href="#">Aprenda espanhol agora!</a>
      </div>
    </div>

    <div class="timeline-item">
      <div class="timeline-icon libras">
      </div>
      <div class="timeline-content">
        <h2>LIBRAS</h2>
        <p class="mt-3">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, facilis quo. Maiores magnam modi ab libero praesentium blanditiis consequatur aspernatur accusantium maxime molestiae sunt ipsa.
        </p>
        <a class="btn btn-flat banner-btn" href="#">Aprenda libras agora!</a>
      </div>
    </div>

    <div class="timeline-item">
      <div class="timeline-icon">
        <span class="fi fi-jp flag-country"></span>
      </div>
      <div class="timeline-content right">
        <h2>JAPONÊS</h2>
        <p class="mt-3">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, facilis quo. Maiores magnam modi ab libero praesentium blanditiis consequatur aspernatur accusantium maxime molestiae sunt ipsa.
        </p>
        <a class="btn btn-flat banner-btn" href="#">Aprenda japonês agora!</a>
      </div>
    </div>

    <div class="timeline-item">
      <div class="timeline-icon">
        <span class="fi fi-kr flag-country"></span>
      </div>
      <div class="timeline-content">
        <h2>COREANO</h2>
        <p class="mt-3">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, facilis quo. Maiores magnam modi ab libero praesentium blanditiis consequatur aspernatur accusantium maxime molestiae sunt ipsa.
        </p>
        <a class="btn btn-flat banner-btn" href="#">Aprenda coreano agora!</a>
      </div>
    </div>

    <div class="timeline-item">
      <div class="timeline-icon">
        <span class="fi fi-de flag-country"></span>
      </div>
      <div class="timeline-content right">
        <h2>ALEMÃO</h2>
        <p class="mt-3">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, facilis quo. Maiores magnam modi ab libero praesentium blanditiis consequatur aspernatur accusantium maxime molestiae sunt ipsa.
        </p>
        <a class="btn btn-flat banner-btn" href="#">Aprenda alemão agora!</a>
      </div>
    </div>

    <div class="timeline-item">
      <div class="timeline-icon">
        <span class="fi fi-fr flag-country"></span>
      </div>
      <div class="timeline-content">
        <h2>FRANCÊS</h2>
        <p class="mt-3">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, facilis quo. Maiores magnam modi ab libero praesentium blanditiis consequatur aspernatur accusantium maxime molestiae sunt ipsa.
        </p>
        <a class="btn btn-flat banner-btn" href="#">Aprenda francês agora!</a>
      </div>
    </div>

    <div class="timeline-item">
      <div class="timeline-icon">
        <span class="fi fi-it flag-country"></span>
      </div>
      <div class="timeline-content right">
        <h2>ITALIANO</h2>
        <p class="mt-3">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, facilis quo. Maiores magnam modi ab libero praesentium blanditiis consequatur aspernatur accusantium maxime molestiae sunt ipsa.
        </p>
        <a class="btn btn-flat banner-btn" href="#">Aprenda italiano agora!</a>
      </div>
    </div>
	</div>
</div>

app/views/pages/home.html.erb
<%= render "banner" %>

<div class="row d-flex justify-content-evenly" style="margin-right: 0;">
  <%= render "timeline" %>
  <div class="p-4 bg-white col-lg-3" style="height: 450px; border-radius: 10px;">
    <%= render partial: 'form_apply', locals: { student: @student } %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/payments/new.html.erb
<div class="container">
  <h1 class="title-text">New Payment</h1>

  <%= simple_form_for [@student, @payment] do |f| %>
    <div class="row student-text"><%= f.input :price %></div>
    <div class="row student-text"><%= f.input :month, collection: Payment.months.values %></div>
    <%= f.submit class: 'btn btn-success' %>
  <% end %>
  <%= link_to 'Back', student_path(@student), class: "btn btn-primary mt-2" %>
</div>

app/views/payments/student_index.html.erb
<div class="container info-student">
  <div class="d-flex flex-column align-items-center mt-3">
    <h1 class="title-text"><%= @student.name %>'s Payements</h1>
  </div>
  <div class="card my-5 card-list">
    <div class="col-12">
      <div class="mx-3">
        <div class="container">
          <% @payments.each do |payment| %>
            <div class="d-flex">
              <span class="row title-text me-3">R$<%= payment.price %> - <%= Payment.months[payment.month ]%></span>
              <%= link_to student_payment_path(student_id: payment.student_id,id: payment.id), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %>
                <i class="fa-solid fa-trash"></i>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to 'Back', student_path(@student), class: "btn btn-primary mt-2 me-2" %>
    <%= link_to 'New payment', new_student_payment_path(@student), class: "btn btn-success mt-2" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright d-flex align-items-center">
    <h4 class="me-2">TAKE THE PINK PILL WITH</h4>
    <%= link_to root_path do %>
      <%= image_tag "logo-azul.png", style: "width: 100px" %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="w-100 d-flex justify-content-center">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-azul.png", style: "width: 60px;" %>
    <% end %>
  </div>
  <div class="container-fluid" style="width: auto;">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <div>
            <li class="nav-item">
              <%= link_to "Students", students_path, class: "nav-link" %>
            </li>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Entrar", new_user_session_path, class: "nav-link me-3" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= simple_form_for(@student) do |f| %>
  <div class="row"><%= f.input :name, placeholder: "Enter student name" %></div>
  <div class="row"><%= f.input :monthly_lessons %></div>
  <div class="row">
    <div class="col-6"><%= f.input :language, collection: Student.languages.keys %></div>
    <div class="col-6"><%= f.input :level, collection: Student.levels.keys %></div>
  </div>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

<%= link_to 'Back', students_path, class: "btn btn-primary mt-2" %>

app/views/students/index.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid justify-content-between">
    <%= link_to root_path do %>
      <i class="fa-solid fa-arrow-left-long fa-lg heading d-none"></i>
    <% end %>
    <h2 class="text-center my-2 heading title-text">My Students</h2>
    <%= link_to new_student_path do %>
      <i class="fa-solid fa-plus fa-lg heading"></i>
    <% end %>
  </div>
</nav>
<div class="container mt-2">
  <div class="row">
    <% @students.each do |student| %>
      <div class="col-6 my-2">
        <div class="card-student" >
          <%= link_to student_path(student), class:"text-decoration-none" do %>
            <p class="mb-3 student-text text-center"><strong><%= student.name.capitalize %></strong></p>
            <p class="mb-3 student-text text-center"><strong><%= Student.languages[student.language] %></strong></p>
            <%= link_to student_path(student), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "m-2 text-decoration-none" do %>
              <i class="fa-solid fa-trash"></i>
            <% end %>
            <%= link_to edit_student_path(student) do %>
              <i class="fa-solid fa-pen-to-square"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/students/show.html.erb
<nav class="navbar navbar-inverse mark-list">
  <div class="container-fluid justify-content-between">
    <%= link_to students_path do %>
      <i class="fa-solid fa-arrow-left-long fa-lg"></i>
    <% end %>
    <h2 class="title-text"><%= @student.name.capitalize %></h2>

    <li class="nav-item dropdown">
      <button class="dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa-solid fa-gear"></i>
      </button>
      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <%= link_to new_student_payment_path(@student), class:"dropdown-item" do %>
          <i class="fa-regular fa-money-bill-1" style="color: #118f00;"></i> Add Payment
        <% end %>
        <%= link_to student_student_payment_index_path(@student), class:"dropdown-item" do %>
          <i class="fa-regular fa-money-bill-1" style="color: #118f00;"></i> View Payments
        <% end %>
        <%= link_to edit_student_path(@student), class:"dropdown-item" do %>
          <i class="fa-solid fa-pen-to-square fa-lg"></i> Edit
        <% end %>
        <%= link_to student_path(@student), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"dropdown-item" do %>
          <i class="fa-solid fa-trash-can fa-lg" style="color: #c30404;"></i> Delete
        <% end %>
      </div>
    </li>
  </div>
</nav>

<div class="container info-student">
  <div class="card my-5 card-list">
    <div class="row mt-2">
      <div class="col-12">
        <div class="mx-3">
        <p><strong>Monthly Lessons: </strong><%= @student.monthly_lessons %></p>
        <p><strong>language: </strong><%= Student.languages[@student.language] %></p>
        <p><strong>Level: </strong><%= Student.levels[@student.level] %></p>
        </div>
      </div>
    </div>
  </div>
</div>



<!--
<% @student_lessons.each_with_index do |student_lesson, index| %>
  <div>
    <% if @student_classes_given[index] %>
      <input type="checkbox" id="<% index %>" class="class-given checked" checked />
    <% else %>
      <input type="checkbox" id="<% index %>" name="lesson-<% index %>" class="class-given" value="lesson-<% index %>" />
    <% end %>
    <label for="<% index %>">Aula <%= index + 1 %></label>
  </div>

<% end %>
<button class="btn btn-primary save" id="save">Salvar</button>

<%= link_to "back", students_path, class: "btn btn-primary" %>


<script>
  const saveClassGivenBtn = document.querySelector('.save')

  const checkBoxesInput = document.querySelectorAll('.class-given')

  checkBoxesInput.forEach((checkBoxInput) => {
    checkBoxInput.addEventListener('click', (event) => {
      event.preventDefault()
      console.log(event.target.classList)
      // event.target.classList.toggle('checked')
    })
  })

  if(saveClassGivenBtn){
    saveClassGivenBtn.addEventListener('click', (event) => {
      event.preventDefault()
      const classGivenCheckBoxes = document.querySelectorAll('.checked')
      console.log(classGivenCheckBoxes.length)
    })
  }
</script>
-->

app/views/wordings/new.html.erb
<%= simple_form_for @wording do |f| %>
  <%= f.input :text %>
  <%= f.input :level, collection: Wording.levels.keys.map {|key| Wording.levels[key]} %>
  <%= f.input :author %>
  <%= f.button :submit %>
<% end %>